version: "3.2"
services:
  consumer:
    image: booking-api-consumer
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
    environment:
      - spring.rabbitmq.host=rabbitmq
    networks:
      - rabbitmq_go_net
  producer:
    image: booking-api-producer
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
    environment:
      - spring.rabbitmq.host=rabbitmq
    networks:
      - rabbitmq_go_net
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net: