server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    password: guest
    username: guest
    exchange: message.exchange
    keys:
      booking:
        add: booking.add.key
        edit: booking.edit.key
        delete: booking.delete.key